module JsonApiServer.PokeUtil

open SharedTypes.Types

let allPokemon =
    [
        { id = 1; num = "001"; name = "Bulbasaur"; img = "http://www.serebii.net/pokemongo/pokemon/001.png"; pokemonType = [ Grass; Poison ]; height = 0.71; weight = 6.9; weaknesses = [ Fire; Ice; Flying; Psychic ]; previousEvolutions = []; nextEvolutions = [{ num = "002"; name = "Ivysaur"}; { num = "003"; name = "Venasaur"}] }
        { id = 2; num = "002"; name = "Ivysaur"; img = "http://www.serebii.net/pokemongo/pokemon/002.png"; pokemonType = [ Grass; Poison ]; height = 0.99; weight = 13.0; weaknesses = [ Fire; Ice; Flying; Psychic ]; previousEvolutions = []; nextEvolutions = [{ num = "003"; name = "Venasaur"}] }
        { id = 3; num = "003"; name = "Venusaur"; img = "http://www.serebii.net/pokemongo/pokemon/003.png"; pokemonType = [ Grass; Poison ]; height = 2.01; weight = 100.0; weaknesses = [ Fire; Ice; Flying; Psychic ]; previousEvolutions = [ { num = "001"; name = "Bulbasaur" }; { num = "002"; name = "Ivysaur" } ]; nextEvolutions = [] }
        { id = 4; num = "004"; name = "Charmander"; img = "http://www.serebii.net/pokemongo/pokemon/004.png"; pokemonType = [ Fire ]; height = 0.61; weight = 8.5; weaknesses = [ Water; Ground; Rock ]; previousEvolutions = []; nextEvolutions = [ { num = "005"; name = "Charmeleon"};  { num = "006"; name = "Charizard" } ] }
        { id = 5; num = "005"; name = "Charmeleon"; img = "http://www.serebii.net/pokemongo/pokemon/005.png"; pokemonType = [ Fire ]; height = 1.09; weight = 19.0; weaknesses = [ Water; Ground; Rock ]; previousEvolutions = [ { num = "004"; name = "Charmander" } ]; nextEvolutions = [ { num = "006"; name = "Charizard" } ] }
        { id = 6; num = "006"; name = "Charizard"; img = "http://www.serebii.net/pokemongo/pokemon/006.png"; pokemonType = [ Fire; Flying ]; height = 1.70; weight = 90.5; weaknesses = [ Water; Electric; Rock ]; previousEvolutions = [ { num = "004"; name = "Charmander" }; { num = "005"; name = "Charmeleon" } ]; nextEvolutions = [] }
        { id = 7; num = "007"; name = "Squirtle"; img = "http://www.serebii.net/pokemongo/pokemon/007.png"; pokemonType = [ Water ]; height = 0.51; weight = 9.0; weaknesses = [ Electric; Grass ]; previousEvolutions = []; nextEvolutions = [ { num = "008"; name = "Wartortle" }; { num = "009"; name = "Blastoise" } ] }
        { id = 8; num = "008"; name = "Wartortle"; img = "http://www.serebii.net/pokemongo/pokemon/008.png"; pokemonType = [ Water ]; height = 0.99; weight = 22.5; weaknesses = [ Electric; Grass ]; previousEvolutions = [{ num = "007"; name = "Squirtle" }]; nextEvolutions = [{ num = "009"; name = "Blastoise" }]}
        { id = 9; num = "009"; name = "Blastoise"; img = "http://www.serebii.net/pokemongo/pokemon/009.png"; pokemonType = [ Water ]; height = 1.60; weight = 85.5; weaknesses = [ Electric; Grass ]; previousEvolutions = [ { num = "007"; name = "Squirtle" }; { num = "008"; name = "Wartortle" } ]; nextEvolutions = [] }
        { id = 10; num = "010"; name = "Caterpie"; img = "http://www.serebii.net/pokemongo/pokemon/010.png"; pokemonType = [ Bug ]; height = 0.30; weight = 2.9; weaknesses = [ Fire; Flying; Rock ]; previousEvolutions = []; nextEvolutions = [ { num = "011"; name = "Metapod"}; { num = "012"; name = "Butterfree" } ] }
        { id = 11; num = "011"; name = "Metapod"; img = "http://www.serebii.net/pokemongo/pokemon/011.png"; pokemonType = [ Bug ]; height = 0.71; weight = 9.9; weaknesses = [ Fire; Flying; Rock ]; previousEvolutions = [ { num = "010"; name = "Caterpie" } ]; nextEvolutions = [ { num = "012"; name = "Butterfree" } ] }
        { id = 12; num = "012"; name = "Butterfree"; img = "http://www.serebii.net/pokemongo/pokemon/012.png"; pokemonType = [ Bug; Flying ]; height = 1.09; weight = 32.0; weaknesses = [ Fire; Electric; Ice; Flying; Rock ]; previousEvolutions = [ { num = "010"; name = "Caterpie"}; { num = "011"; name = "Metapod" }]; nextEvolutions = [] }
        { id = 13; num = "013"; name = "Weedle"; img = "http://www.serebii.net/pokemongo/pokemon/013.png"; pokemonType = [ Bug; Poison ]; height = 0.30; weight = 3.2; weaknesses = [ Fire; Flying; Psychic; Rock ]; previousEvolutions = []; nextEvolutions = [ { num = "014"; name = "Kakuna" }; { num = "015"; name = "Beedrill" } ] }
        { id = 14; num = "014"; name = "Kakuna"; img = "http://www.serebii.net/pokemongo/pokemon/014.png"; pokemonType = [ Bug; Poison ]; height = 0.61; weight = 10.0; weaknesses = [ Fire; Flying; Psychic; Rock ]; previousEvolutions = [ { num = "013"; name = "Weedle" } ]; nextEvolutions = [ { num = "015"; name = "Beedrill" } ] }
        { id = 15; num = "015"; name = "Beedrill"; img = "http://www.serebii.net/pokemongo/pokemon/015.png"; pokemonType = [ Bug; Poison ]; height = 0.99; weight = 29.5; weaknesses = [ Fire; Flying; Psychic; Rock ]; previousEvolutions = [ { num = "013"; name = "Weedle" }; { num = "014"; name = "Kakuna" } ]; nextEvolutions = [] }
        { id = 16; num = "016"; name = "Pidgey"; img = "http://www.serebii.net/pokemongo/pokemon/016.png"; pokemonType = [ Normal; Flying ]; height = 0.30; weight = 1.8; weaknesses = [ Electric; Rock ]; previousEvolutions = []; nextEvolutions = [ { num = "017"; name = "Pidgeotto" }; { num = "018"; name = "Pidgeot" } ] }
        { id = 17; num = "017"; name = "Pidgeotto"; img = "http://www.serebii.net/pokemongo/pokemon/017.png"; pokemonType = [ Normal; Flying ]; height = 1.09; weight = 30.0; weaknesses = [ Electric; Rock ]; previousEvolutions = [ { num = "016"; name = "Pidgey" } ]; nextEvolutions = [ { num = "018"; name = "Pidgeot" } ] }
        { id = 18; num = "018"; name = "Pidgeot"; img = "http://www.serebii.net/pokemongo/pokemon/018.png"; pokemonType = [ Normal; Flying ]; height = 1.50; weight = 39.5; weaknesses = [ Electric; Rock ]; previousEvolutions = [ { num = "016"; name = "Pidgey" }; { num = "017"; name = "Pidgeotto" } ]; nextEvolutions = [] }
        { id = 19; num = "019"; name = "Rattata"; img = "http://www.serebii.net/pokemongo/pokemon/019.png"; pokemonType = [ Normal ]; height = 0.30; weight = 3.5; weaknesses = [ Fighting ]; previousEvolutions = []; nextEvolutions = [ { num = "020"; name = "Raticate" } ] }
        { id = 20; num = "020"; name = "Raticate"; img = "http://www.serebii.net/pokemongo/pokemon/020.png"; pokemonType = [ Normal ]; height = 0.71; weight = 18.5; weaknesses = [ Fighting ]; previousEvolutions = [ { num = "019"; name = "Rattata" } ]; nextEvolutions = [] }
        { id = 21; num = "021"; name = "Spearow"; img = "http://www.serebii.net/pokemongo/pokemon/021.png"; pokemonType = [ Normal; Flying ]; height = 0.30; weight = 2.0; weaknesses = [ Electric; Rock ]; previousEvolutions = []; nextEvolutions = [ { num = "022"; name = "Fearow" } ] }
        { id = 22; num = "022"; name = "Fearow"; img = "http://www.serebii.net/pokemongo/pokemon/022.png"; pokemonType = [ Normal; Flying ]; height = 1.19; weight = 38.0; weaknesses = [ Electric; Rock ]; previousEvolutions = [ { num = "021"; name = "Spearow" } ]; nextEvolutions = [] }
        { id = 23; num = "023"; name = "Ekans"; img = "http://www.serebii.net/pokemongo/pokemon/023.png"; pokemonType = [ Poison ]; height = 2.01; weight = 6.9; weaknesses = [ Ground; Psychic ]; previousEvolutions = []; nextEvolutions = [ { num = "024"; name = "Arbok" } ] }
        { id = 24; num = "024"; name = "Arbok"; img = "http://www.serebii.net/pokemongo/pokemon/024.png"; pokemonType = [ Poison ]; height = 3.51; weight = 65.0; weaknesses = [ Ground; Psychic ]; previousEvolutions = [ { num = "023"; name = "Ekans" } ]; nextEvolutions = [] }
        { id = 25; num = "025"; name = "Pikachu"; img = "http://www.serebii.net/pokemongo/pokemon/025.png"; pokemonType = [ Electric ]; height = 0.41; weight = 6.0; weaknesses = [ Ground ]; previousEvolutions = []; nextEvolutions = [ { num = "026"; name = "Raichu" } ] }
        { id = 26; num = "026"; name = "Raichu"; img = "http://www.serebii.net/pokemongo/pokemon/026.png"; pokemonType = [ Electric ]; height = 0.79; weight = 30.0; weaknesses = [ Ground ]; previousEvolutions = [ { num = "025"; name = "Pikachu" } ]; nextEvolutions = [] }
        { id = 27; num = "027"; name = "Sandshrew"; img = "http://www.serebii.net/pokemongo/pokemon/027.png"; pokemonType = [ Ground ]; height = 0.61; weight = 12.0; weaknesses = [ Water; Grass; Ice ]; previousEvolutions = []; nextEvolutions = [ { num = "028"; name = "Sandslash" } ] }
        { id = 28; num = "028"; name = "Sandslash"; img = "http://www.serebii.net/pokemongo/pokemon/028.png"; pokemonType = [ Ground ]; height = 0.99; weight = 29.5; weaknesses = [ Water; Grass; Ice ]; previousEvolutions = [ { num = "027"; name = "Sandshrew" } ]; nextEvolutions = [] }
        { id = 29; num = "029"; name = "Nidoran ♀ (Female)"; img = "http://www.serebii.net/pokemongo/pokemon/029.png"; pokemonType = [ Poison ]; height = 0.41; weight = 7.0; weaknesses = [ Ground; Psychic ]; previousEvolutions = []; nextEvolutions = [ { num = "030"; name = "Nidorina" }; { num = "031"; name = "Nidoqueen" } ] }
        { id = 30; num = "030"; name = "Nidorina"; img = "http://www.serebii.net/pokemongo/pokemon/030.png"; pokemonType = [ Poison ]; height = 0.79; weight = 20.0; weaknesses = [ Ground; Psychic ]; previousEvolutions = [ { num = "029"; name = "Nidoran(Female)" } ]; nextEvolutions = [ { num = "031"; name = "Nidoqueen" } ] }
        { id = 31; num = "031"; name = "Nidoqueen"; img = "http://www.serebii.net/pokemongo/pokemon/031.png"; pokemonType = [ Poison; Ground ]; height = 1.30; weight = 60.0; weaknesses = [ Water; Ice; Ground; Psychic ]; previousEvolutions = [ { num = "029"; name = "Nidoran(Female)" }; { num = "030"; name = "Nidorina" } ]; nextEvolutions = [] }
        { id = 32; num = "032"; name = "Nidoran ♂ (Male)"; img = "http://www.serebii.net/pokemongo/pokemon/032.png"; pokemonType = [ Poison ]; height = 0.51; weight = 9.0; weaknesses = [ Ground; Psychic ]; previousEvolutions = []; nextEvolutions = [ { num = "033"; name = "Nidorino" }; { num = "034"; name = "Nidoking" } ] }
        { id = 33; num = "033"; name = "Nidorino"; img = "http://www.serebii.net/pokemongo/pokemon/033.png"; pokemonType = [ Poison ]; height = 0.89; weight = 19.5; weaknesses = [ Ground; Psychic ]; previousEvolutions = [ { num = "032"; name = "Nidoran(Male)" } ]; nextEvolutions = [ { num = "034"; name = "Nidoking" } ] }
        { id = 34; num = "034"; name = "Nidoking"; img = "http://www.serebii.net/pokemongo/pokemon/034.png"; pokemonType = [ Poison; Ground ]; height = 1.40; weight = 62.0; weaknesses = [ Water; Ice; Ground; Psychic ]; previousEvolutions = [ { num = "032"; name = "Nidoran(Male)" }; { num = "033"; name = "Nidorino" } ]; nextEvolutions = [] }
        { id = 35; num = "035"; name = "Clefairy"; img = "http://www.serebii.net/pokemongo/pokemon/035.png"; pokemonType = [ Normal ]; height = 0.61; weight = 7.5; weaknesses = [ Fighting ]; previousEvolutions = []; nextEvolutions = [ { num = "036"; name = "Clefable" } ] }
        { id = 36; num = "036"; name = "Clefable"; img = "http://www.serebii.net/pokemongo/pokemon/036.png"; pokemonType = [ Normal ]; height = 1.30; weight = 40.0; weaknesses = [ Fighting ]; previousEvolutions = [ { num = "035"; name = "Clefairy" } ]; nextEvolutions = [] }
        { id = 37; num = "037"; name = "Vulpix"; img = "http://www.serebii.net/pokemongo/pokemon/037.png"; pokemonType = [ Fire ]; height = 0.61; weight = 9.9; weaknesses = [ Water; Ground; Rock ]; previousEvolutions = []; nextEvolutions = [ { num = "038"; name = "Ninetales" } ] }
        { id = 38; num = "038"; name = "Ninetales"; img = "http://www.serebii.net/pokemongo/pokemon/038.png"; pokemonType = [ Fire ]; height = 1.09; weight = 19.9; weaknesses = [ Water; Ground; Rock ]; previousEvolutions = [ { num = "037"; name = "Vulpix" } ]; nextEvolutions = [] }
        { id = 39; num = "039"; name = "Jigglypuff"; img = "http://www.serebii.net/pokemongo/pokemon/039.png"; pokemonType = [ Normal ]; height = 0.51; weight = 5.5; weaknesses = [ Fighting ]; previousEvolutions = []; nextEvolutions = [ { num = "040"; name = "Wigglytuff" } ] }
        { id = 40; num = "040"; name = "Wigglytuff"; img = "http://www.serebii.net/pokemongo/pokemon/040.png"; pokemonType = [ Normal ]; height = 0.99; weight = 12.0; weaknesses = [ Fighting ]; previousEvolutions = [ { num = "039"; name = "Jigglypuff" } ]; nextEvolutions = [] }
        { id = 41; num = "041"; name = "Zubat"; img = "http://www.serebii.net/pokemongo/pokemon/041.png"; pokemonType = [ Poison; Flying ]; height = 0.79; weight = 7.5; weaknesses = [ Electric; Ice; Psychic; Rock ]; previousEvolutions = []; nextEvolutions = [ { num = "042"; name = "Golbat" } ] }
        { id = 42; num = "042"; name = "Golbat"; img = "http://www.serebii.net/pokemongo/pokemon/042.png"; pokemonType = [ Poison; Flying ]; height = 1.60; weight = 55.0; weaknesses = [ Electric; Ice; Psychic; Rock ]; previousEvolutions = [ { num = "041"; name = "Zubat" } ]; nextEvolutions = [] }
        { id = 43; num = "043"; name = "Oddish"; img = "http://www.serebii.net/pokemongo/pokemon/043.png"; pokemonType = [ Grass; Poison ]; height = 0.51; weight = 5.4; weaknesses = [ Fire; Ice; Flying; Psychic ]; previousEvolutions = []; nextEvolutions = [ { num = "044"; name = "Gloom" }; { num = "045"; name = "Vileplume" } ] }
        { id = 44; num = "044"; name = "Gloom"; img = "http://www.serebii.net/pokemongo/pokemon/044.png"; pokemonType = [ Grass; Poison ]; height = 0.79; weight = 8.6; weaknesses = [ Fire; Ice; Flying; Psychic ]; previousEvolutions = [ { num = "043"; name = "Oddish" } ]; nextEvolutions = [ { num = "045"; name = "Vileplume" } ] }
        { id = 45; num = "045"; name = "Vileplume"; img = "http://www.serebii.net/pokemongo/pokemon/045.png"; pokemonType = [ Grass; Poison ]; height = 1.19; weight = 18.6; weaknesses = [ Fire; Ice; Flying; Psychic ]; previousEvolutions = [ { num = "043"; name = "Oddish" }; { num = "044"; name = "Gloom" } ]; nextEvolutions = [] }
        { id = 46; num = "046"; name = "Paras"; img = "http://www.serebii.net/pokemongo/pokemon/046.png"; pokemonType = [ Bug; Grass ]; height = 0.30; weight = 5.4; weaknesses = [ Fire; Ice; Poison; Flying; Bug; Rock ]; previousEvolutions = []; nextEvolutions = [ { num = "047"; name = "Parasect" } ] }
        { id = 47; num = "047"; name = "Parasect"; img = "http://www.serebii.net/pokemongo/pokemon/047.png"; pokemonType = [ Bug; Grass ]; height = 0.99; weight = 29.5; weaknesses = [ Fire; Ice; Poison; Flying; Bug; Rock ]; previousEvolutions = [ { num = "046"; name = "Paras" } ]; nextEvolutions = [] }
        { id = 48; num = "048"; name = "Venonat"; img = "http://www.serebii.net/pokemongo/pokemon/048.png"; pokemonType = [ Bug; Poison ]; height = 0.99; weight = 30.0; weaknesses = [ Fire; Flying; Psychic; Rock ]; previousEvolutions = []; nextEvolutions = [ { num = "049"; name = "Venomoth" } ] }
        { id = 49; num = "049"; name = "Venomoth"; img = "http://www.serebii.net/pokemongo/pokemon/049.png"; pokemonType = [ Bug; Poison ]; height = 1.50; weight = 12.5; weaknesses = [ Fire; Flying; Psychic; Rock ]; previousEvolutions = [ { num = "048"; name = "Venonat" } ]; nextEvolutions = [] }
        { id = 50; num = "050"; name = "Diglett"; img = "http://www.serebii.net/pokemongo/pokemon/050.png"; pokemonType = [ Ground ]; height = 0.20; weight = 0.8; weaknesses = [ Water; Grass; Ice ]; previousEvolutions = []; nextEvolutions = [ { num = "051"; name = "Dugtrio" } ] }
        { id = 51; num = "051"; name = "Dugtrio"; img = "http://www.serebii.net/pokemongo/pokemon/051.png"; pokemonType = [ Ground ]; height = 0.71; weight = 33.3; weaknesses = [ Water; Grass; Ice ]; previousEvolutions = [ { num = "050"; name = "Diglett" } ]; nextEvolutions = [] }
        { id = 52; num = "052"; name = "Meowth"; img = "http://www.serebii.net/pokemongo/pokemon/052.png"; pokemonType = [ Normal ]; height = 0.41; weight = 4.2; weaknesses = [ Fighting ]; previousEvolutions = []; nextEvolutions = [ { num = "053"; name = "Persian" } ] }
        { id = 53; num = "053"; name = "Persian"; img = "http://www.serebii.net/pokemongo/pokemon/053.png"; pokemonType = [ Normal ]; height = 0.99; weight = 32.0; weaknesses = [ Fighting ]; previousEvolutions = [ { num = "052"; name = "Meowth" } ]; nextEvolutions = [] }
        { id = 54; num = "054"; name = "Psyduck"; img = "http://www.serebii.net/pokemongo/pokemon/054.png"; pokemonType = [ Water ]; height = 0.79; weight = 19.6; weaknesses = [ Electric; Grass ]; previousEvolutions = []; nextEvolutions = [ { num = "055"; name = "Golduck" } ] }
        { id = 55; num = "055"; name = "Golduck"; img = "http://www.serebii.net/pokemongo/pokemon/055.png"; pokemonType = [ Water ]; height = 1.70; weight = 76.6; weaknesses = [ Electric; Grass ]; previousEvolutions = [ { num = "054"; name = "Psyduck" } ]; nextEvolutions = [] }
        { id = 56; num = "056"; name = "Mankey"; img = "http://www.serebii.net/pokemongo/pokemon/056.png"; pokemonType = [ Fighting ]; height = 0.51; weight = 28.0; weaknesses = [ Flying; Psychic; Fairy ]; previousEvolutions = []; nextEvolutions = [ { num = "057"; name = "Primeape" } ] }
        { id = 57; num = "057"; name = "Primeape"; img = "http://www.serebii.net/pokemongo/pokemon/057.png"; pokemonType = [ Fighting ]; height = 0.99; weight = 32.0; weaknesses = [ Flying; Psychic; Fairy ]; previousEvolutions = [ { num = "056"; name = "Mankey" } ]; nextEvolutions = [] }
        { id = 58; num = "058"; name = "Growlithe"; img = "http://www.serebii.net/pokemongo/pokemon/058.png"; pokemonType = [ Fire ]; height = 0.71; weight = 19.0; weaknesses = [ Water; Ground; Rock ]; previousEvolutions = []; nextEvolutions = [ { num = "059"; name = "Arcanine" } ] }
        { id = 59; num = "059"; name = "Arcanine"; img = "http://www.serebii.net/pokemongo/pokemon/059.png"; pokemonType = [ Fire ]; height = 1.91; weight = 155.0; weaknesses = [ Water; Ground; Rock ]; previousEvolutions = [ { num = "058"; name = "Growlithe" } ]; nextEvolutions = [] }
        { id = 60; num = "060"; name = "Poliwag"; img = "http://www.serebii.net/pokemongo/pokemon/060.png"; pokemonType = [ Water ]; height = 0.61; weight = 12.4; weaknesses = [ Electric; Grass ]; previousEvolutions = []; nextEvolutions = [ { num = "061"; name = "Poliwhirl" }; { num = "062"; name = "Poliwrath" } ] }
        { id = 61; num = "061"; name = "Poliwhirl"; img = "http://www.serebii.net/pokemongo/pokemon/061.png"; pokemonType = [ Water ]; height = 0.99; weight = 20.0; weaknesses = [ Electric; Grass ]; previousEvolutions = [ { num = "060"; name = "Poliwag" } ]; nextEvolutions = [ { num = "062"; name = "Poliwrath" } ] }
        { id = 62; num = "062"; name = "Poliwrath"; img = "http://www.serebii.net/pokemongo/pokemon/062.png"; pokemonType = [ Water; Fighting ]; height = 1.30; weight = 54.0; weaknesses = [ Electric; Grass; Flying; Psychic; Fairy ]; previousEvolutions = [ { num = "060"; name = "Poliwag" }; { num = "061"; name = "Poliwhirl" } ]; nextEvolutions = [] }
        { id = 63; num = "063"; name = "Abra"; img = "http://www.serebii.net/pokemongo/pokemon/063.png"; pokemonType = [ Psychic ]; height = 0.89; weight = 19.5; weaknesses = [ Bug; Ghost; Dark ]; previousEvolutions = []; nextEvolutions = [ { num = "064"; name = "Kadabra" }; { num = "065"; name = "Alakazam" } ] }
        { id = 64; num = "064"; name = "Kadabra"; img = "http://www.serebii.net/pokemongo/pokemon/064.png"; pokemonType = [ Psychic ]; height = 1.30; weight = 56.5; weaknesses = [ Bug; Ghost; Dark ]; previousEvolutions = [ { num = "063"; name = "Abra" } ]; nextEvolutions = [ { num = "065"; name = "Alakazam" } ] }
        { id = 65; num = "065"; name = "Alakazam"; img = "http://www.serebii.net/pokemongo/pokemon/065.png"; pokemonType = [ Psychic ]; height = 1.50; weight = 48.0; weaknesses = [ Bug; Ghost; Dark ]; previousEvolutions = [ { num = "063"; name = "Abra" }; { num = "064"; name = "Kadabra" } ]; nextEvolutions = [] }
        { id = 66; num = "066"; name = "Machop"; img = "http://www.serebii.net/pokemongo/pokemon/066.png"; pokemonType = [ Fighting ]; height = 0.79; weight = 19.5; weaknesses = [ Flying; Psychic; Fairy ]; previousEvolutions = []; nextEvolutions = [ { num = "067"; name = "Machoke" }; { num = "068"; name = "Machamp" } ] }
        { id = 67; num = "067"; name = "Machoke"; img = "http://www.serebii.net/pokemongo/pokemon/067.png"; pokemonType = [ Fighting ]; height = 1.50; weight = 70.5; weaknesses = [ Flying; Psychic; Fairy ]; previousEvolutions = [ { num = "066"; name = "Machop" } ]; nextEvolutions = [ { num = "068"; name = "Machamp" } ] }
        { id = 68; num = "068"; name = "Machamp"; img = "http://www.serebii.net/pokemongo/pokemon/068.png"; pokemonType = [ Fighting ]; height = 1.60; weight = 130.0; weaknesses = [ Flying; Psychic; Fairy ]; previousEvolutions = [ { num = "066"; name = "Machop" }; { num = "067"; name = "Machoke" } ]; nextEvolutions = [] }
        { id = 69; num = "069"; name = "Bellsprout"; img = "http://www.serebii.net/pokemongo/pokemon/069.png"; pokemonType = [ Grass; Poison ]; height = 0.71; weight = 4.0; weaknesses = [ Fire; Ice; Flying; Psychic ]; previousEvolutions = []; nextEvolutions = [ { num = "070"; name = "Weepinbell" }; { num = "071"; name = "Victreebel" } ] }
        { id = 70; num = "070"; name = "Weepinbell"; img = "http://www.serebii.net/pokemongo/pokemon/070.png"; pokemonType = [ Grass; Poison ]; height = 0.99; weight = 6.4; weaknesses = [ Fire; Ice; Flying; Psychic ]; previousEvolutions = [ { num = "069"; name = "Bellsprout" } ]; nextEvolutions = [ { num = "071"; name = "Victreebel" } ] }
        { id = 71; num = "071"; name = "Victreebel"; img = "http://www.serebii.net/pokemongo/pokemon/071.png"; pokemonType = [ Grass; Poison ]; height = 1.70; weight = 15.5; weaknesses = [ Fire; Ice; Flying; Psychic ]; previousEvolutions = [ { num = "069"; name = "Bellsprout" }; { num = "070"; name = "Weepinbell" } ]; nextEvolutions = [] }
        { id = 72; num = "072"; name = "Tentacool"; img = "http://www.serebii.net/pokemongo/pokemon/072.png"; pokemonType = [ Water; Poison ]; height = 0.89; weight = 45.5; weaknesses = [ Electric; Ground; Psychic ]; previousEvolutions = []; nextEvolutions = [ { num = "073"; name = "Tentacruel" } ] }
        { id = 73; num = "073"; name = "Tentacruel"; img = "http://www.serebii.net/pokemongo/pokemon/073.png"; pokemonType = [ Water; Poison ]; height = 1.60; weight = 55.0; weaknesses = [ Electric; Ground; Psychic ]; previousEvolutions = [ { num = "072"; name = "Tentacool" } ]; nextEvolutions = [] }
        { id = 74; num = "074"; name = "Geodude"; img = "http://www.serebii.net/pokemongo/pokemon/074.png"; pokemonType = [ Rock; Ground ]; height = 0.41; weight = 20.0; weaknesses = [ Water; Grass; Ice; Fighting; Ground; Steel ]; previousEvolutions = []; nextEvolutions = [ { num = "075"; name = "Graveler" }; { num = "076"; name = "Golem" } ] }
        { id = 75; num = "075"; name = "Graveler"; img = "http://www.serebii.net/pokemongo/pokemon/075.png"; pokemonType = [ Rock; Ground ]; height = 0.99; weight = 105.0; weaknesses = [ Water; Grass; Ice; Fighting; Ground; Steel ]; previousEvolutions = [ { num = "074"; name = "Geodude" } ]; nextEvolutions = [ { num = "076"; name = "Golem" } ] }
        { id = 76; num = "076"; name = "Golem"; img = "http://www.serebii.net/pokemongo/pokemon/076.png"; pokemonType = [ Rock; Ground ]; height = 1.40; weight = 300.0; weaknesses = [ Water; Grass; Ice; Fighting; Ground; Steel ]; previousEvolutions = [ { num = "074"; name = "Geodude" }; { num = "075"; name = "Graveler" } ]; nextEvolutions = [] }
        { id = 77; num = "077"; name = "Ponyta"; img = "http://www.serebii.net/pokemongo/pokemon/077.png"; pokemonType = [ Fire ]; height = 0.99; weight = 30.0; weaknesses = [ Water; Ground; Rock ]; previousEvolutions = []; nextEvolutions = [ { num = "078"; name = "Rapidash" } ] }
        { id = 78; num = "078"; name = "Rapidash"; img = "http://www.serebii.net/pokemongo/pokemon/078.png"; pokemonType = [ Fire ]; height = 1.70; weight = 95.0; weaknesses = [ Water; Ground; Rock ]; previousEvolutions = [ { num = "077"; name = "Ponyta" } ]; nextEvolutions = [] }
        { id = 79; num = "079"; name = "Slowpoke"; img = "http://www.serebii.net/pokemongo/pokemon/079.png"; pokemonType = [ Water; Psychic ]; height = 1.19; weight = 36.0; weaknesses = [ Electric; Grass; Bug; Ghost; Dark ]; previousEvolutions = []; nextEvolutions = [ { num = "080"; name = "Slowbro" } ] }
        { id = 80; num = "080"; name = "Slowbro"; img = "http://www.serebii.net/pokemongo/pokemon/080.png"; pokemonType = [ Water; Psychic ]; height = 1.60; weight = 78.5; weaknesses = [ Electric; Grass; Bug; Ghost; Dark ]; previousEvolutions = [ { num = "079"; name = "Slowpoke" } ]; nextEvolutions = [] }
        { id = 81; num = "081"; name = "Magnemite"; img = "http://www.serebii.net/pokemongo/pokemon/081.png"; pokemonType = [ Electric ]; height = 0.30; weight = 6.0; weaknesses = [ Fire; Water; Ground ]; previousEvolutions = []; nextEvolutions = [ { num = "082"; name = "Magneton" } ] }
        { id = 82; num = "082"; name = "Magneton"; img = "http://www.serebii.net/pokemongo/pokemon/082.png"; pokemonType = [ Electric ]; height = 0.99; weight = 60.0; weaknesses = [ Fire; Water; Ground ]; previousEvolutions = [ { num = "081"; name = "Magnemite" } ]; nextEvolutions = [] }
        { id = 83; num = "083"; name = "Farfetch'd"; img = "http://www.serebii.net/pokemongo/pokemon/083.png"; pokemonType = [ Normal; Flying ]; height = 0.79; weight = 15.0; weaknesses = [ Electric; Rock ]; previousEvolutions = []; nextEvolutions = [] }
        { id = 84; num = "084"; name = "Doduo"; img = "http://www.serebii.net/pokemongo/pokemon/084.png"; pokemonType = [ Normal; Flying ]; height = 1.40; weight = 39.2; weaknesses = [ Electric; Rock ]; previousEvolutions = []; nextEvolutions = [ { num = "085"; name = "Dodrio" } ] }
        { id = 85; num = "085"; name = "Dodrio"; img = "http://www.serebii.net/pokemongo/pokemon/085.png"; pokemonType = [ Normal; Flying ]; height = 1.80; weight = 85.2; weaknesses = [ Electric; Rock ]; previousEvolutions = [ { num = "084"; name = "Doduo" } ]; nextEvolutions = [] }
        { id = 86; num = "086"; name = "Seel"; img = "http://www.serebii.net/pokemongo/pokemon/086.png"; pokemonType = [ Water ]; height = 1.09; weight = 90.0; weaknesses = [ Electric; Grass ]; previousEvolutions = []; nextEvolutions = [ { num = "087"; name = "Dewgong" } ] }
        { id = 87; num = "087"; name = "Dewgong"; img = "http://www.serebii.net/pokemongo/pokemon/087.png"; pokemonType = [ Water; Ice ]; height = 1.70; weight = 120.0; weaknesses = [ Electric; Grass; Fighting; Rock ]; previousEvolutions = [ { num = "086"; name = "Seel" } ]; nextEvolutions = [] }
        { id = 88; num = "088"; name = "Grimer"; img = "http://www.serebii.net/pokemongo/pokemon/088.png"; pokemonType = [ Poison ]; height = 0.89; weight = 30.0; weaknesses = [ Ground; Psychic ]; previousEvolutions = []; nextEvolutions = [ { num = "089"; name = "Muk" } ] }
        { id = 89; num = "089"; name = "Muk"; img = "http://www.serebii.net/pokemongo/pokemon/089.png"; pokemonType = [ Poison ]; height = 1.19; weight = 30.0; weaknesses = [ Ground; Psychic ]; previousEvolutions = [ { num = "088"; name = "Grimer" } ]; nextEvolutions = [] }
        { id = 90; num = "090"; name = "Shellder"; img = "http://www.serebii.net/pokemongo/pokemon/090.png"; pokemonType = [ Water ]; height = 0.30; weight = 4.0; weaknesses = [ Electric; Grass ]; previousEvolutions = []; nextEvolutions = [ { num = "091"; name = "Cloyster" } ] }
        { id = 91; num = "091"; name = "Cloyster"; img = "http://www.serebii.net/pokemongo/pokemon/091.png"; pokemonType = [ Water; Ice ]; height = 1.50; weight = 132.5; weaknesses = [ Electric; Grass; Fighting; Rock ]; previousEvolutions = [ { num = "090"; name = "Shellder" } ]; nextEvolutions = [] }
        { id = 92; num = "092"; name = "Gastly"; img = "http://www.serebii.net/pokemongo/pokemon/092.png"; pokemonType = [ Ghost; Poison ]; height = 1.30; weight = 0.1; weaknesses = [ Ground; Psychic; Ghost; Dark ]; previousEvolutions = []; nextEvolutions = [ { num = "093"; name = "Haunter" }; { num = "094"; name = "Gengar" } ] }
        { id = 93; num = "093"; name = "Haunter"; img = "http://www.serebii.net/pokemongo/pokemon/093.png"; pokemonType = [ Ghost; Poison ]; height = 1.60; weight = 0.1; weaknesses = [ Ground; Psychic; Ghost; Dark ]; previousEvolutions = [ { num = "092"; name = "Gastly" } ]; nextEvolutions = [ { num = "094"; name = "Gengar" } ] }
        { id = 94; num = "094"; name = "Gengar"; img = "http://www.serebii.net/pokemongo/pokemon/094.png"; pokemonType = [ Ghost; Poison ]; height = 1.50; weight = 40.5; weaknesses = [ Ground; Psychic; Ghost; Dark ]; previousEvolutions = [ { num = "092"; name = "Gastly" }; { num = "093"; name = "Haunter" } ]; nextEvolutions = [] }
        { id = 95; num = "095"; name = "Onix"; img = "http://www.serebii.net/pokemongo/pokemon/095.png"; pokemonType = [ Rock; Ground ]; height = 8.79; weight = 210.0; weaknesses = [ Water; Grass; Ice; Fighting; Ground; Steel ]; previousEvolutions = []; nextEvolutions = [] }
        { id = 96; num = "096"; name = "Drowzee"; img = "http://www.serebii.net/pokemongo/pokemon/096.png"; pokemonType = [ Psychic ]; height = 0.99; weight = 32.4; weaknesses = [ Bug; Ghost; Dark ]; previousEvolutions = []; nextEvolutions = [ { num = "097"; name = "Hypno" } ] }
        { id = 97; num = "097"; name = "Hypno"; img = "http://www.serebii.net/pokemongo/pokemon/097.png"; pokemonType = [ Psychic ]; height = 1.60; weight = 75.6; weaknesses = [ Bug; Ghost; Dark ]; previousEvolutions = [ { num = "096"; name = "Drowzee" } ]; nextEvolutions = [] }
        { id = 98; num = "098"; name = "Krabby"; img = "http://www.serebii.net/pokemongo/pokemon/098.png"; pokemonType = [ Water ]; height = 0.41; weight = 6.5; weaknesses = [ Electric; Grass ]; previousEvolutions = []; nextEvolutions = [ { num = "099"; name = "Kingler" } ] }
        { id = 99; num = "099"; name = "Kingler"; img = "http://www.serebii.net/pokemongo/pokemon/099.png"; pokemonType = [ Water ]; height = 1.30; weight = 60.0; weaknesses = [ Electric; Grass ]; previousEvolutions = [ { num = "098"; name = "Krabby" } ]; nextEvolutions = [] }
        { id = 100; num = "100"; name = "Voltorb"; img = "http://www.serebii.net/pokemongo/pokemon/100.png"; pokemonType = [ Electric ]; height = 0.51; weight = 10.4; weaknesses = [ Ground ]; previousEvolutions = []; nextEvolutions = [ { num = "101"; name = "Electrode" } ] }
        { id = 101; num = "101"; name = "Electrode"; img = "http://www.serebii.net/pokemongo/pokemon/101.png"; pokemonType = [ Electric ]; height = 1.19; weight = 66.6; weaknesses = [ Ground ]; previousEvolutions = [ { num = "100"; name = "Voltorb" } ]; nextEvolutions = [] }
        { id = 102; num = "102"; name = "Exeggcute"; img = "http://www.serebii.net/pokemongo/pokemon/102.png"; pokemonType = [ Grass; Psychic ]; height = 0.41; weight = 2.5; weaknesses = [ Fire; Ice; Poison; Flying; Bug; Ghost; Dark ]; previousEvolutions = []; nextEvolutions = [ { num = "103"; name = "Exeggutor" } ] }
        { id = 103; num = "103"; name = "Exeggutor"; img = "http://www.serebii.net/pokemongo/pokemon/103.png"; pokemonType = [ Grass; Psychic ]; height = 2.01; weight = 120.0; weaknesses = [ Fire; Ice; Poison; Flying; Bug; Ghost; Dark ]; previousEvolutions = [ { num = "102"; name = "Exeggcute" } ]; nextEvolutions = [] }
        { id = 104; num = "104"; name = "Cubone"; img = "http://www.serebii.net/pokemongo/pokemon/104.png"; pokemonType = [ Ground ]; height = 0.41; weight = 6.5; weaknesses = [ Water; Grass; Ice ]; previousEvolutions = []; nextEvolutions = [ { num = "105"; name = "Marowak" } ] }
        { id = 105; num = "105"; name = "Marowak"; img = "http://www.serebii.net/pokemongo/pokemon/105.png"; pokemonType = [ Ground ]; height = 0.99; weight = 45.0; weaknesses = [ Water; Grass; Ice ]; previousEvolutions = [ { num = "104"; name = "Cubone" } ]; nextEvolutions = [] }
        { id = 106; num = "106"; name = "Hitmonlee"; img = "http://www.serebii.net/pokemongo/pokemon/106.png"; pokemonType = [ Fighting ]; height = 1.50; weight = 49.8; weaknesses = [ Flying; Psychic; Fairy ]; previousEvolutions = []; nextEvolutions = [] }
        { id = 107; num = "107"; name = "Hitmonchan"; img = "http://www.serebii.net/pokemongo/pokemon/107.png"; pokemonType = [ Fighting ]; height = 1.40; weight = 50.2; weaknesses = [ Flying; Psychic; Fairy ]; previousEvolutions = []; nextEvolutions = [] }
        { id = 108; num = "108"; name = "Lickitung"; img = "http://www.serebii.net/pokemongo/pokemon/108.png"; pokemonType = [ Normal ]; height = 1.19; weight = 65.5; weaknesses = [ Fighting ]; previousEvolutions = []; nextEvolutions = [] }
        { id = 109; num = "109"; name = "Koffing"; img = "http://www.serebii.net/pokemongo/pokemon/109.png"; pokemonType = [ Poison ]; height = 0.61; weight = 1.0; weaknesses = [ Ground; Psychic ]; previousEvolutions = []; nextEvolutions = [ { num = "110"; name = "Weezing" } ] }
        { id = 110; num = "110"; name = "Weezing"; img = "http://www.serebii.net/pokemongo/pokemon/110.png"; pokemonType = [ Poison ]; height = 1.19; weight = 9.5; weaknesses = [ Ground; Psychic ]; previousEvolutions = [ { num = "109"; name = "Koffing" } ]; nextEvolutions = [] }
        { id = 111; num = "111"; name = "Rhyhorn"; img = "http://www.serebii.net/pokemongo/pokemon/111.png"; pokemonType = [ Ground; Rock ]; height = 0.99; weight = 115.0; weaknesses = [ Water; Grass; Ice; Fighting; Ground; Steel ]; previousEvolutions = []; nextEvolutions = [ { num = "112"; name = "Rhydon" } ] }
        { id = 112; num = "112"; name = "Rhydon"; img = "http://www.serebii.net/pokemongo/pokemon/112.png"; pokemonType = [ Ground; Rock ]; height = 1.91; weight = 120.0; weaknesses = [ Water; Grass; Ice; Fighting; Ground; Steel ]; previousEvolutions = [ { num = "111"; name = "Rhyhorn" } ]; nextEvolutions = [] }
        { id = 113; num = "113"; name = "Chansey"; img = "http://www.serebii.net/pokemongo/pokemon/113.png"; pokemonType = [ Normal ]; height = 1.09; weight = 34.6; weaknesses = [ Fighting ]; previousEvolutions = []; nextEvolutions = [] }
        { id = 114; num = "114"; name = "Tangela"; img = "http://www.serebii.net/pokemongo/pokemon/114.png"; pokemonType = [ Grass ]; height = 0.99; weight = 35.0; weaknesses = [ Fire; Ice; Poison; Flying; Bug ]; previousEvolutions = []; nextEvolutions = [] }
        { id = 115; num = "115"; name = "Kangaskhan"; img = "http://www.serebii.net/pokemongo/pokemon/115.png"; pokemonType = [ Normal ]; height = 2.21; weight = 80.0; weaknesses = [ Fighting ]; previousEvolutions = []; nextEvolutions = [] }
        { id = 116; num = "116"; name = "Horsea"; img = "http://www.serebii.net/pokemongo/pokemon/116.png"; pokemonType = [ Water ]; height = 0.41; weight = 8.0; weaknesses = [ Electric; Grass ]; previousEvolutions = []; nextEvolutions = [ { num = "117"; name = "Seadra" } ] }
        { id = 117; num = "117"; name = "Seadra"; img = "http://www.serebii.net/pokemongo/pokemon/117.png"; pokemonType = [ Water ]; height = 1.19; weight = 25.0; weaknesses = [ Electric; Grass ]; previousEvolutions = [ { num = "116"; name = "Horsea" } ]; nextEvolutions = [] }
        { id = 118; num = "118"; name = "Goldeen"; img = "http://www.serebii.net/pokemongo/pokemon/118.png"; pokemonType = [ Water ]; height = 0.61; weight = 15.0; weaknesses = [ Electric; Grass ]; previousEvolutions = []; nextEvolutions = [ { num = "119"; name = "Seaking" } ] }
        { id = 119; num = "119"; name = "Seaking"; img = "http://www.serebii.net/pokemongo/pokemon/119.png"; pokemonType = [ Water ]; height = 1.30; weight = 39.0; weaknesses = [ Electric; Grass ]; previousEvolutions = [ { num = "118"; name = "Goldeen" } ]; nextEvolutions = [] }
        { id = 120; num = "120"; name = "Staryu"; img = "http://www.serebii.net/pokemongo/pokemon/120.png"; pokemonType = [ Water ]; height = 0.79; weight = 34.5; weaknesses = [ Electric; Grass ]; previousEvolutions = []; nextEvolutions = [ { num = "121"; name = "Starmie" } ] }
        { id = 121; num = "121"; name = "Starmie"; img = "http://www.serebii.net/pokemongo/pokemon/121.png"; pokemonType = [ Water; Psychic ]; height = 1.09; weight = 80.0; weaknesses = [ Electric; Grass; Bug; Ghost; Dark ]; previousEvolutions = [ { num = "120"; name = "Staryu" } ]; nextEvolutions = [] }
        { id = 122; num = "122"; name = "Mr.ime"; img = "http://www.serebii.net/pokemongo/pokemon/122.png"; pokemonType = [ Psychic ]; height = 1.30; weight = 54.5; weaknesses = [ Bug; Ghost; Dark ]; previousEvolutions = []; nextEvolutions = [] }
        { id = 123; num = "123"; name = "Scyther"; img = "http://www.serebii.net/pokemongo/pokemon/123.png"; pokemonType = [ Bug; Flying ]; height = 1.50; weight = 56.0; weaknesses = [ Fire; Electric; Ice; Flying; Rock ]; previousEvolutions = []; nextEvolutions = [] }
        { id = 124; num = "124"; name = "Jynx"; img = "http://www.serebii.net/pokemongo/pokemon/124.png"; pokemonType = [ Ice; Psychic ]; height = 1.40; weight = 40.6; weaknesses = [ Fire; Bug; Rock; Ghost; Dark; Steel ]; previousEvolutions = []; nextEvolutions = [] }
        { id = 125; num = "125"; name = "Electabuzz"; img = "http://www.serebii.net/pokemongo/pokemon/125.png"; pokemonType = [ Electric ]; height = 1.09; weight = 30.0; weaknesses = [ Ground ]; previousEvolutions = []; nextEvolutions = [] }
        { id = 126; num = "126"; name = "Magmar"; img = "http://www.serebii.net/pokemongo/pokemon/126.png"; pokemonType = [ Fire ]; height = 1.30; weight = 44.5; weaknesses = [ Water; Ground; Rock ]; previousEvolutions = []; nextEvolutions = [] }
        { id = 127; num = "127"; name = "Pinsir"; img = "http://www.serebii.net/pokemongo/pokemon/127.png"; pokemonType = [ Bug ]; height = 1.50; weight = 55.0; weaknesses = [ Fire; Flying; Rock ]; previousEvolutions = []; nextEvolutions = [] }
        { id = 128; num = "128"; name = "Tauros"; img = "http://www.serebii.net/pokemongo/pokemon/128.png"; pokemonType = [ Normal ]; height = 1.40; weight = 88.4; weaknesses = [ Fighting ]; previousEvolutions = []; nextEvolutions = [] }
        { id = 129; num = "129"; name = "Magikarp"; img = "http://www.serebii.net/pokemongo/pokemon/129.png"; pokemonType = [ Water ]; height = 0.89; weight = 10.0; weaknesses = [ Electric; Grass ]; previousEvolutions = []; nextEvolutions = [ { num = "130"; name = "Gyarados" } ] }
        { id = 130; num = "130"; name = "Gyarados"; img = "http://www.serebii.net/pokemongo/pokemon/130.png"; pokemonType = [ Water; Flying ]; height = 6.50; weight = 235.0; weaknesses = [ Electric; Rock ]; previousEvolutions = [ { num = "129"; name = "Magikarp" } ]; nextEvolutions = [] }
        { id = 131; num = "131"; name = "Lapras"; img = "http://www.serebii.net/pokemongo/pokemon/131.png"; pokemonType = [ Water; Ice ]; height = 2.49; weight = 220.0; weaknesses = [ Electric; Grass; Fighting; Rock ]; previousEvolutions = []; nextEvolutions = [] }
        { id = 132; num = "132"; name = "Ditto"; img = "http://www.serebii.net/pokemongo/pokemon/132.png"; pokemonType = [ Normal ]; height = 0.30; weight = 4.0; weaknesses = [ Fighting ]; previousEvolutions = []; nextEvolutions = [] }
        { id = 133; num = "133"; name = "Eevee"; img = "http://www.serebii.net/pokemongo/pokemon/133.png"; pokemonType = [ Normal ]; height = 0.30; weight = 6.5; weaknesses = [ Fighting ]; previousEvolutions = []; nextEvolutions = [ { num = "134"; name = "Vaporeon" }; { num = "135"; name = "Jolteon" }; { num = "136"; name = "Flareon" } ] }
        { id = 134; num = "134"; name = "Vaporeon"; img = "http://www.serebii.net/pokemongo/pokemon/134.png"; pokemonType = [ Water ]; height = 0.99; weight = 29.0; weaknesses = [ Electric; Grass ]; previousEvolutions = [ { num = "133"; name = "Eevee" } ]; nextEvolutions = [] }
        { id = 135; num = "135"; name = "Jolteon"; img = "http://www.serebii.net/pokemongo/pokemon/135.png"; pokemonType = [ Electric ]; height = 0.79; weight = 24.5; weaknesses = [ Ground ]; previousEvolutions = [ { num = "133"; name = "Eevee" } ]; nextEvolutions = [] }
        { id = 136; num = "136"; name = "Flareon"; img = "http://www.serebii.net/pokemongo/pokemon/136.png"; pokemonType = [ Fire ]; height = 0.89; weight = 25.0; weaknesses = [ Water; Ground; Rock ]; previousEvolutions = [ { num = "133"; name = "Eevee" } ]; nextEvolutions = [] }
        { id = 137; num = "137"; name = "Porygon"; img = "http://www.serebii.net/pokemongo/pokemon/137.png"; pokemonType = [ Normal ]; height = 0.79; weight = 36.5; weaknesses = [ Fighting ]; previousEvolutions = []; nextEvolutions = [] }
        { id = 138; num = "138"; name = "Omanyte"; img = "http://www.serebii.net/pokemongo/pokemon/138.png"; pokemonType = [ Rock; Water ]; height = 0.41; weight = 7.5; weaknesses = [ Electric; Grass; Fighting; Ground ]; previousEvolutions = []; nextEvolutions = [ { num = "139"; name = "Omastar" } ] }
        { id = 139; num = "139"; name = "Omastar"; img = "http://www.serebii.net/pokemongo/pokemon/139.png"; pokemonType = [ Rock; Water ]; height = 0.99; weight = 35.0; weaknesses = [ Electric; Grass; Fighting; Ground ]; previousEvolutions = [ { num = "138"; name = "Omanyte" } ]; nextEvolutions = [] }
        { id = 140; num = "140"; name = "Kabuto"; img = "http://www.serebii.net/pokemongo/pokemon/140.png"; pokemonType = [ Rock; Water ]; height = 0.51; weight = 11.5; weaknesses = [ Electric; Grass; Fighting; Ground ]; previousEvolutions = []; nextEvolutions = [ { num = "141"; name = "Kabutops" } ] }
        { id = 141; num = "141"; name = "Kabutops"; img = "http://www.serebii.net/pokemongo/pokemon/141.png"; pokemonType = [ Rock; Water ]; height = 1.30; weight = 40.5; weaknesses = [ Electric; Grass; Fighting; Ground ]; previousEvolutions = [ { num = "140"; name = "Kabuto" } ]; nextEvolutions = [] }
        { id = 142; num = "142"; name = "Aerodactyl"; img = "http://www.serebii.net/pokemongo/pokemon/142.png"; pokemonType = [ Rock; Flying ]; height = 1.80; weight = 59.0; weaknesses = [ Water; Electric; Ice; Rock; Steel ]; previousEvolutions = []; nextEvolutions = [] }
        { id = 143; num = "143"; name = "Snorlax"; img = "http://www.serebii.net/pokemongo/pokemon/143.png"; pokemonType = [ Normal ]; height = 2.11; weight = 460.0; weaknesses = [ Fighting ]; previousEvolutions = []; nextEvolutions = [] }
        { id = 144; num = "144"; name = "Articuno"; img = "http://www.serebii.net/pokemongo/pokemon/144.png"; pokemonType = [ Ice; Flying ]; height = 1.70; weight = 55.4; weaknesses = [ Fire; Electric; Rock; Steel ]; previousEvolutions = []; nextEvolutions = [] }
        { id = 145; num = "145"; name = "Zapdos"; img = "http://www.serebii.net/pokemongo/pokemon/145.png"; pokemonType = [ Electric; Flying ]; height = 1.60; weight = 52.6; weaknesses = [ Ice; Rock ]; previousEvolutions = []; nextEvolutions = [] }
        { id = 146; num = "146"; name = "Moltres"; img = "http://www.serebii.net/pokemongo/pokemon/146.png"; pokemonType = [ Fire; Flying ]; height = 2.01; weight = 60.0; weaknesses = [ Water; Electric; Rock ]; previousEvolutions = []; nextEvolutions = [] }
        { id = 147; num = "147"; name = "Dratini"; img = "http://www.serebii.net/pokemongo/pokemon/147.png"; pokemonType = [ Dragon ]; height = 1.80; weight = 3.3; weaknesses = [ Ice; Dragon; Fairy ]; previousEvolutions = []; nextEvolutions = [ { num = "148"; name = "Dragonair" }; { num = "149"; name = "Dragonite" } ] }
        { id = 148; num = "148"; name = "Dragonair"; img = "http://www.serebii.net/pokemongo/pokemon/148.png"; pokemonType = [ Dragon ]; height = 3.99; weight = 16.5; weaknesses = [ Ice; Dragon; Fairy ]; previousEvolutions = [ { num = "147"; name = "Dratini" } ]; nextEvolutions = [ { num = "149"; name = "Dragonite" } ] }
        { id = 149; num = "149"; name = "Dragonite"; img = "http://www.serebii.net/pokemongo/pokemon/149.png"; pokemonType = [ Dragon; Flying ]; height = 2.21; weight = 210.0; weaknesses = [ Ice; Rock; Dragon; Fairy ]; previousEvolutions = [ { num = "147"; name = "Dratini" }; { num = "148"; name = "Dragonair" } ]; nextEvolutions = [] }
        { id = 150; num = "150"; name = "Mewtwo"; img = "http://www.serebii.net/pokemongo/pokemon/150.png"; pokemonType = [ Psychic ]; height = 2.01; weight = 122.0; weaknesses = [ Bug; Ghost; Dark ]; previousEvolutions = []; nextEvolutions = [] }
        { id = 151; num = "151"; name = "Mew"; img = "http://www.serebii.net/pokemongo/pokemon/151.png"; pokemonType = [ Psychic ]; height = 0.41; weight = 4.0; weaknesses = [ Bug; Ghost; Dark ]; previousEvolutions = []; nextEvolutions = [] }
    ]